env_type: d4rl
env_name: metaworld_ml10
metadata_path: data/metaworld/metadata.json
num_clients: 10
random_select_clients: false
rounds: 100
cpus_per_client: 2
n_steps: 4096
update_epochs: 10
minibatch_size: 64
hidden_dim: 256
lr: 1e-4
gamma: 0.99
gae_lambda: 0.95
clip_eps: 0.2
entropy_coef: 0.0
value_coef: 0.5
max_grad_norm: 0.5
lambda_global: 0
lambda_local: 0
eval_episodes: 10

bc_env_name: MetaWorld
bc_root: ./model/bc_policy
bc_blend_alpha: 0.3

output_dir: ./model/policy/metaworld/fedavg
metrics_dir: ./metrics/metaworld/fedavg
save_every: 10
device: auto
gpus_per_client: 0.1
seed: [0]
render_eval: true
render_mode: video
render_save_dir: ./plots/metaworld/fedavg
render_every_n_rounds: 20
render_episodes: 3
render_all_clients: true 
min_fit_clients: 10
min_evaluate_clients: 10
min_available_clients: 10
