env_type: d4rl
env_name: metaworld_ml10
metadata_path: data/metaworld/metadata.json
num_clients: 10
random_select_clients: false
rounds: 50
cpus_per_client: 2
n_steps: 2000
lambda_local: 0.05
lambda_guide: 0.5
lambda_guide_anneal: true
lambda_guide_decay_rounds: 50
update_epochs: 4
minibatch_size: 64
init_log_std: 0.0
aggregate_mode: prior
use_pretrained_models: true
prior_adapt_fallback_all: true
prior_dir: ./model/models_prior
bc_dir: ./model/bc_policy
bc_env_name: MetaWorld
moe_enable: true
num_experts_prior: 8
num_experts_guidance: 8
ot_mode: sinkhorn
ot_reg: 0.05
personalized_routing: true
policy_activation: tanh
action_clamp_low: -1.0
action_clamp_high: 1.0
log_std_anneal: false
log_std_anneal_rounds: 80
log_std_anneal_target: -1.5
guide_coef: 0.0
guidance_eta: 0.1
use_wandb: false
wandb_project: null
run_name: null
output_dir: ./model/policy/metaworld_phase1/fedguide_prior_strict
metrics_dir: ./metrics/metaworld_phase1/fedguide_prior_strict
collect_metrics_every: 5
gpus_per_client: 0.1
device: auto
seed:
- 0
render_eval: false
render_mode: video
render_save_dir: ./plots/metaworld_phase1/fedguide_prior_strict
render_every_n_rounds: 50
render_episodes: 1
min_fit_clients: 10
min_evaluate_clients: 10
min_available_clients: 10
